In [1]:
!pip install numpy


## Introduction to NumPy
##### In this video, we are going to discuss a very important library called NumPy. Up to this point, we have covered advanced Python concepts such as iterators, generators, and decorators. Now, we are moving to a new module: data analysis with Python. Here, we will focus on libraries like NumPy, Pandas, and visualization libraries such as Matplotlib and Seaborn, which are fundamentally used for data analysis.

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [4]:
print(type(arr1))
print(arr1.shape)

<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])
arr3 = arr2.reshape(2,5) ## 2 rows 5 columns
print(arr3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
print(arr3.shape)

(2, 5)


In [8]:
arr4 = np.array([[1,2,3,4,5] , [6,7,8,9,10]])
print(arr4,"\n","Shape of the array is : ",arr4.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 
 Shape of the array is :  (2, 5)


In [9]:
arr = np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [10]:
arr_reshaped = arr.reshape(5,1)
print(arr_reshaped)

[[0]
 [2]
 [4]
 [6]
 [8]]


In [ ]:
## ones is used to create a martix of ones and .ones function is used for 2D array
ones_arr = np.ones((3,4))
print(ones_arr)
arrOnes = np.ones(3,4)
print(arrOnes)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


TypeError: Cannot interpret '4' as a data type

In [ ]:
## .eye function is used for to create an identity martix
identity_matrix = np.eye(3,4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


## Array Attributes
#### NumPy arrays have several useful attributes such as shape, ndim, size, dtype, and itemsize.

In [ ]:
arr5 =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr5.size) ## number of elements in the given array
print(arr5.shape)
print(arr5.ndim) ## define dimensions 
print(arr5.dtype) ## typye in byte
print(arr5.itemsize) ## bit space of each element

10
(2, 5)
2
int64
8


## Vectorized Operations
##### NumPy supports vectorized operations, allowing you to perform element-wise arithmetic directly on arrays.

In [18]:
arr6 = np.array([3,4,5,6])
arr7 = np.array([10,20,30,40])
print(arr6 + arr7)
print(arr7 - arr6)
print(arr6 * arr7)
print(arr6 / arr7)

[13 24 35 46]
[ 7 16 25 34]
[ 30  80 150 240]
[0.3        0.2        0.16666667 0.15      ]


## Universal Functions
#### NumPy provides universal functions (ufuncs) that operate element-wise on arrays, such as sqrt, exp, sin, and log.

In [19]:
arr8 = np.array([6,7,8,9])
print(np.sqrt(arr8))
print(np.exp(arr8))
print(np.sin(arr8))
print(np.log(arr8))

[2.44948974 2.64575131 2.82842712 3.        ]
[ 403.42879349 1096.63315843 2980.95798704 8103.08392758]
[-0.2794155   0.6569866   0.98935825  0.41211849]
[1.79175947 1.94591015 2.07944154 2.19722458]


## Array Slicing and Indexing
##### You can perform slicing and indexing operations on NumPy arrays, similar to Python lists, but with more power for multi-dimensional arrays.



In [20]:
arr9 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print(arr9)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(arr9[0, 0])
print(arr9[1:3,2:4]) ## first 2 numbers (1:3) represent rows and last 2 numbers (2:4) represent column number
print(arr9[2]) ## use for to access a single row
print(arr9[:2]) ## use for to access multiple rows
print(arr9[:,2]) ## use for to access a specific column

1
[[ 7  8]
 [11 12]]
[ 9 10 11 12]
[[1 2 3 4]
 [5 6 7 8]]
[ 3  7 11]


In [28]:
print(arr9[:,1:3])

[[ 2  3]
 [ 6  7]
 [10 11]]


In [29]:
arr9

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
## we can iterate array also
for i in arr9:
    print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [31]:
for i in np.nditer(arr9):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


## .ravel() function 
##### it is used for to convert 1D,2D,3D array into 1D array

In [32]:
print(arr9.ravel())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [33]:
arr9

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
print(arr9.transpose())

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [36]:
arr10 = np.arange(1,11)
print(arr10)

[ 1  2  3  4  5  6  7  8  9 10]


In [37]:
print(arr10.reshape(2,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [40]:
arr11 = arr10.reshape(2,5)
print(arr11)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [41]:
print(arr11.transpose())

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


## Stacking
#### it is used for to merge 2 arrays

In [42]:
arr_ = np.arange(2,8)
arr_0 = np.arange(8,17)
print(arr_,"\n",arr_0)

[2 3 4 5 6 7] 
 [ 8  9 10 11 12 13 14 15 16]


In [44]:
print(np.hstack((arr_,arr_0)))

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [46]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(data > 5)
print(data[data > 5])
print(data[(data > 5) & (data < 9)])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[6 7 8]


## Statistical Operations and Normalization
##### NumPy provides functions for statistical operations such as mean, median, standard deviation, and variance. Normalization is a common operation where data is transformed to have a mean of zero and a standard deviation of one.



In [47]:
data1 = np.array([1,2,3,4,5])
# calculate the mean and deviation
mean = np.mean(data1)
std_dev = np.std(data1)
# formula is 
normalized_data = (data1 - mean) / std_dev
print("Normalized data is : ",normalized_data)

Normalized data is :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [48]:
data2 = np.arange(14,31)
print(np.mean(data2))
print(np.median(data2))
print(np.std(data2))
print(np.var(data2))

22.0
22.0
4.898979485566356
24.0
